// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    baseUrl: '../',
    enforceDefine: true,
    paths: {
      jasmine: 'lib/jasmine/jasmine',
      'jasmine-html': 'lib/jasmine/jasmine-html',
      'jquery-mockjax': 'lib/jquery.mockjax'
    },
    shim: {
      jasmine: {
        exports: 'jasmine'
      },
      'jasmine-html': {
        deps: ['jasmine'],
        exports: 'jasmine'
      },
      'jquery-mockjax': {
        deps: ['jquery'],
        exports: 'jQuery'
      }
    },
    config: {
      i18n: {
        warn: true
      }
    }
  });

}).call(this);
