// Generated by CoffeeScript 1.3.3
(function() {

  define('SpecRunner', ['jquery', 'jasmine-html'], function(jQuery, jasmine) {
    var htmlReporter, jasmineEnv, specs;
    specs = ['spec/MetadataSpec.js'];
    jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 1000;
    htmlReporter = new jasmine.HtmlReporter();
    jasmineEnv.addReporter(htmlReporter);
    jasmineEnv.specFilter = function(spec) {
      return htmlReporter.specFilter(spec);
    };
    return jQuery(function() {
      return require(specs, function() {
        return jasmineEnv.execute();
      });
    });
  });

}).call(this);
