// Generated by CoffeeScript 1.3.3
(function() {

  require.onError = function(err) {
    return console.error(err);
  };

  require.config({
    paths: {
      aloha: '../Aloha-Editor/src/lib/aloha'
    }
  });

  require(['app/models'], function(Models) {
    Models.ALL_CONTENT.add({
      id: 'test1',
      mediaType: 'text/x-module',
      title: 'Test Module',
      body: '<h1>Hello</h1>'
    });
    Models.ALL_CONTENT.add({
      id: 'test2',
      mediaType: 'text/x-module',
      title: 'Another Test Module',
      body: '<h1>Hello2</h1>'
    });
    Models.ALL_CONTENT.add({
      id: 'col1',
      mediaType: 'text/x-collection',
      title: 'Test Collection',
      navTree: [
        {
          title: 'Test 1',
          href: 'test1'
        }, {
          title: 'Bob',
          href: 'test2'
        }
      ]
    });
    Models.SearchResults = Models.SearchResults.extend({
      initialize: function() {
        var model, _i, _len, _ref, _results;
        _ref = Models.ALL_CONTENT.models;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          model = _ref[_i];
          _results.push(this.add(model));
        }
        return _results;
      }
    });
    return Models.ALL_CONTENT.each(function(model) {
      return model.loaded = true;
    });
  });

}).call(this);
