// Generated by CoffeeScript 1.3.3
(function() {

  define({
    'root': {
      'gray': 'grey',
      'blue': 'azul',
      'green': 'verde',
      'fr': false,
      'en-ca': false
    }
  });

}).call(this);
