// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone', 'exports', 'app/urls', 'i18n!app/nls/strings'], function(Backbone, exports, URLS, __) {
    var ALL_CONTENT, Content, factory;
    Content = Backbone.Model.extend({
      defaults: {
        title: __('Untitled'),
        subjects: [],
        keywords: [],
        authors: [],
        copyrightHolders: [],
        language: ((typeof navigator !== "undefined" && navigator !== null ? navigator.userLanguage : void 0) || (typeof navigator !== "undefined" && navigator !== null ? navigator.language : void 0) || 'en').toLowerCase()
      },
      url: function() {
        if (this.get('id')) {
          return "" + URLS.CONTENT_PREFIX + (this.get('id'));
        } else {
          return URLS.CONTENT_PREFIX;
        }
      },
      validate: function(attrs) {
        var isEmpty;
        isEmpty = function(str) {
          return str && !str.trim().length;
        };
        if (isEmpty(attrs.body)) {
          return 'ERROR_EMPTY_BODY';
        }
        if (isEmpty(attrs.title)) {
          return 'ERROR_EMPTY_TITLE';
        }
        if (attrs.title === __('Untitled')) {
          return 'ERROR_UNTITLED_TITLE';
        }
      }
    });
    exports.SearchResultItem = Backbone.Model.extend({
      defaults: {
        type: 'content',
        title: 'BUG_UNSPECIFIED_TITLE'
      },
      getContent: function() {
        return exports.getContent(this.get('id'));
      }
    });
    exports.Workspace = Backbone.Collection.extend({
      model: exports.SearchResultItem,
      url: URLS.WORKSPACE
    });
    ALL_CONTENT = new Backbone.Collection();
    factory = function(constructor, key) {
      var model,
        _this = this;
      model = ALL_CONTENT.get(key);
      if (!model) {
        model = new constructor({
          id: key
        });
        ALL_CONTENT.add(model);
        model.fetch({
          error: function() {
            return alert("Problem fetching " + key);
          },
          success: function() {
            return model._loaded = true;
          }
        });
      }
      return ALL_CONTENT.get(key);
    };
    exports.getContent = function(href) {
      return factory(ALL_CONTENT, Content, href);
    };
    exports.Content = Content;
    return exports;
  });

}).call(this);
