// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone', 'exports', 'i18n!app/nls/strings'], function(Backbone, exports, __) {
    var ALL_CONTENT, AllContent, BaseContent, Book, Content, Deferrable, DeferrableCollection, MEDIA_TYPES, MediaTypes, SearchResults, deferred;
    MediaTypes = Backbone.Collection.extend({
      model: Backbone.Model.extend({
        sync: function() {
          throw 'This model cannot be syncd';
        }
      }),
      sync: function() {
        throw 'This model cannot be syncd';
      }
    });
    MEDIA_TYPES = new MediaTypes();
    BaseContent = Backbone.Model.extend({
      initialize: function() {
        var key, mediaType, mediaTypeConfig, proto, value;
        mediaType = this.get('mediaType');
        if (!mediaType) {
          throw 'BUG: No mediaType set';
        }
        if (!MEDIA_TYPES.get(mediaType)) {
          throw 'BUG: No mediaType not registered';
        }
        mediaTypeConfig = MEDIA_TYPES.get(mediaType);
        proto = mediaTypeConfig.get('constructor').prototype;
        for (key in proto) {
          value = proto[key];
          this[key] = value;
        }
        return proto.initialize.apply(this, arguments);
      }
    });
    AllContent = Backbone.Collection.extend({
      model: BaseContent
    });
    ALL_CONTENT = new AllContent();
    deferred = function(cb) {
      var _this = this;
      if (this.loaded) {
        return cb(null, this);
      }
      if (!this._defer) {
        this._defer = this.fetch();
      }
      return this._defer.done(function(value) {
        _this.loaded = true;
        _this._defer = null;
        return cb(null, _this);
      }).fail(function(err) {
        _this.loaded = false;
        _this._defer = null;
        return cb(err, _this);
      });
    };
    Deferrable = Backbone.Model.extend({
      deferred: function() {
        return deferred.apply(this, arguments);
      }
    });
    DeferrableCollection = Backbone.Collection.extend({
      deferred: function() {
        return deferred.apply(this, arguments);
      }
    });
    Content = Deferrable.extend({
      defaults: {
        title: __('Untitled'),
        subjects: [],
        keywords: [],
        authors: [],
        copyrightHolders: [],
        language: ((typeof navigator !== "undefined" && navigator !== null ? navigator.userLanguage : void 0) || (typeof navigator !== "undefined" && navigator !== null ? navigator.language : void 0) || 'en').toLowerCase()
      },
      url: function() {
        if (this.get('id')) {
          return "" + URLS.CONTENT_PREFIX + (this.get('id'));
        } else {
          return URLS.CONTENT_PREFIX;
        }
      },
      validate: function(attrs) {
        var isEmpty;
        isEmpty = function(str) {
          return str && !str.trim().length;
        };
        if (isEmpty(attrs.body)) {
          return 'ERROR_EMPTY_BODY';
        }
        if (isEmpty(attrs.title)) {
          return 'ERROR_EMPTY_TITLE';
        }
        if (attrs.title === __('Untitled')) {
          return 'ERROR_UNTITLED_TITLE';
        }
      }
    });
    Book = Deferrable.extend({
      defaults: {
        manifest: null,
        navTree: null
      },
      parseNavTree: function(li) {
        var $a, $li, $ol, $span, obj;
        $li = jQuery(li);
        $a = $li.children('a');
        $span = $li.children('span');
        $ol = $li.children('ol');
        if ($a[0]) {
          obj = {
            href: $a.attr('href'),
            title: $a.text()
          };
        } else {
          obj = {
            title: $span.text()
          };
        }
        if ($ol[0]) {
          obj.children = (function() {
            var _i, _len, _ref, _results;
            _ref = $ol.children();
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              li = _ref[_i];
              _results.push(this.parseNavTree(li));
            }
            return _results;
          }).call(this);
        }
        return obj;
      },
      deferred: function() {
        return deferred.apply(this, arguments);
      },
      initialize: function() {
        this.manifest = new Backbone.Collection();
        return this.manifest.on('add', function(model) {
          return ALL_CONTENT.add(model);
        });
      }
    });
    SearchResults = DeferrableCollection.extend({
      defaults: {
        parameters: []
      }
    });
    MEDIA_TYPES.add({
      id: 'text/x-module',
      constructor: Content
    });
    MEDIA_TYPES.add({
      id: 'text/x-collection',
      constructor: Book
    });
    exports.ALL_CONTENT = ALL_CONTENT;
    exports.MEDIA_TYPES = MEDIA_TYPES;
    exports.SearchResults = SearchResults;
    return exports;
  });

}).call(this);
