// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    return {
      ME: '/me',
      CONTENT_PREFIX: '/content/',
      WORKSPACE: '/workspace/',
      KEYWORDS: '/keywords/',
      USERS: '/users/'
    };
  });

}).call(this);
