// Generated by CoffeeScript 1.3.3
(function() {

  define(['underscore', 'backbone'], function(_, Backbone) {
    var AuthModel;
    AuthModel = Backbone.Model.extend({
      me: function(usersCollection) {
        var _this = this;
        return _.find(usersCollection, function(user) {
          return _this.isMe;
        });
      },
      isMe: function(user) {
        return userId === user.get('id');
      },
      signOut: function() {
        return this.set('id', null, {
          unset: true
        });
      }
    });
    return new AuthModel();
  });

}).call(this);
